[package]
name = "raffle-core"
version = "0.1.0"
authors = ["Maayan Hanin <maayan.asa.hanin@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.55"
rand =  { version = "0.7.3", features = ["wasm-bindgen"] }

[profile.release]
opt-level = "s"
